### ISSUE TITLE
Themes

### ISSUE THREAD

**Issue by tjwrona** [tnt-coders/rock-buddy-app#3]
Having the option to switch between multiple themes (light mode, dark mode, other options as well) would be really nice to allow each user to customize their experience to their liking.

**Comment by SpicyDoritos** [comment]
Theme system has been setup and 3 themes have been added, it is setup so more can easily be added in the future =) 

Dark/Light/Streamer Mode

**Comment by tjwrona** [comment]
Reopening because I think if I tie it to the pull request it will auto-close when the pull request is merged and keep track of history better :)
