### ISSUE TITLE
Verified scores do not work on some charts.

### ISSUE THREAD

**Issue by tjwrona** [tnt-coders/rock-buddy-app#58]
Starting a thread to list specific charts. Comment any charts you find below.

**Comment by tjwrona** [comment]
Currents - The Death We Seek (v1.1 - Lil Ramen Noodle)
Mors Principium Est - The Forsaken (v1 - incore97)

**Comment by Jssome** [comment]
Megadeth - Vortex (v1 - DarkSanitarium) - Note count mismatch

**Comment by tjwrona** [comment]
Most of these are solved in 9ea8597a7795287af6bd36891acc28abc5e6f715

Creating a new issue to track additional songs that don't work with verified scores
