### ISSUE TITLE
Charts seem to go unverified unexpectedly on slower PCs

### ISSUE THREAD

**Issue by tjwrona** [tnt-coders/rock-buddy-app#66]
See attached log for examples

[rock-buddy-log.txt](https://github.com/tnt-coders/rock-buddy-app/files/11877244/rock-buddy-log.txt)

**Comment by IronDeuce** [comment]
[rock-buddy-log.txt](https://github.com/tnt-coders/rock-buddy-app/files/11932329/rock-buddy-log.txt)

**Comment by IronDeuce** [comment]
[rock-buddy-log.txt](https://github.com/tnt-coders/rock-buddy-app/files/11992348/rock-buddy-log.txt)

**Comment by IronDeuce** [comment]
[rock-buddy-log.txt](https://github.com/tnt-coders/rock-buddy-app/files/11995483/rock-buddy-log.txt)

**Comment by tjwrona** [comment]
Thanks @IronDeuce I'll start digging into these and see if I can find anything!

**Comment by tjwrona** [comment]
Patched in v1.1.8

If this still seems to be a problem feel free to reopen the issue.

**Comment by Dk-Pepper** [comment]
I am currently having this issue after updating to 1.6.2 where it thinks I am pausing the song while playing
