### ISSUE TITLE
Problem with leader board in LaS mode (BASS path)

### ISSUE THREAD

**Issue by PoizenJam** [tnt-coders/rock-buddy-app#67]
Rock-Buddy, I'm flattered, but I clearly am not the #1 slot for Interpol - Slow Hands on Bass. ;)

edit: it just occurred to me this may reflect preferential ranking of verified/unverified scores?

<img width="617" alt="Untitled" src="https://github.com/tnt-coders/rock-buddy-app/assets/65501967/1df6440e-65d3-412a-94d9-dc03d06bee0b">

**Comment by tjwrona** [comment]
Hi @PoizenJam you are correct. Verified scores are always on top since Rock Buddy knows for sure you didn't cheat :)
