### ISSUE TITLE
2 computer streaming setup

### ISSUE THREAD

**Issue by Skippern** [tnt-coders/rock-buddy-app#69]
Instruction on how to set up scene/source in OBS when using a 2 computer streaming setup.

**Comment by tjwrona** [comment]
Hi @Skippern I should write up a guide on how to do this, but basically you run Rock Buddy on the same PC that Rocksmith runs on, then you put the Rock Buddy addons (they're in the addons.zip file included in the release on github) on your streaming PC that runs OBS. 

Then in the rock buddy config, set the Addons host to the IP address of your gaming PC (the one running Rock Buddy). Note you have to put the actual IP address here. "localhost" will not work.

![image](https://github.com/tnt-coders/rock-buddy-app/assets/44857895/ca861fe0-caeb-4944-b553-429e9de9de31)

Then on your streaming PC (the one running OBS) edit the "config.js" file located in the addons folder to point to the IP of your gaming PC (the same IP you entered in the rock buddy config display) and also make sure the port numbers match.

Then you can include Rock Buddy in OBS using the capture.html file in the addons as a browser source.

Feel free to DM me in discord if you have any more questions. I'll probably respond quicker there than on Github lol

**Comment by tjwrona** [comment]
Added a section at the end of the FAQ on the https://rock-buddy.com website :)
